/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
    package bank;
    
    import javax.swing.JOptionPane;
/**
 *
 * @author Icha
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bsaldo = new javax.swing.JButton();
        btransfer = new javax.swing.JButton();
        bsetor = new javax.swing.JButton();
        btarik = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ttransfer = new javax.swing.JTextField();
        tsetor = new javax.swing.JTextField();
        ttarik = new javax.swing.JTextField();
        show = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bsaldo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsaldo.setText("Informasi Saldo");
        bsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaldoActionPerformed(evt);
            }
        });
        getContentPane().add(bsaldo);
        bsaldo.setBounds(37, 90, 130, 50);

        btransfer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btransfer.setText("Transfer");
        btransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btransferActionPerformed(evt);
            }
        });
        getContentPane().add(btransfer);
        btransfer.setBounds(270, 330, 150, 50);

        bsetor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsetor.setText("Penyetoran");
        bsetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsetorActionPerformed(evt);
            }
        });
        getContentPane().add(bsetor);
        bsetor.setBounds(40, 160, 130, 50);

        btarik.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btarik.setText("Penarikan");
        btarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btarikActionPerformed(evt);
            }
        });
        getContentPane().add(btarik);
        btarik.setBounds(270, 260, 150, 50);

        bkeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bkeluar.setText("Log out");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar);
        bkeluar.setBounds(60, 420, 100, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BANK BAROKAH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 190, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Siap Melayani dengan Segenap hati");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 30, 310, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Sisa Saldo Anda : Rp");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 100, 190, 40);
        getContentPane().add(ttransfer);
        ttransfer.setBounds(60, 330, 180, 40);
        getContentPane().add(tsetor);
        tsetor.setBounds(200, 170, 180, 40);
        getContentPane().add(ttarik);
        ttarik.setBounds(60, 260, 180, 40);

        show.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(show);
        show.setBounds(390, 100, 160, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Icha\\Downloads\\uwiuw.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 570, 470);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btransferActionPerformed
        // TODO add your handling code here:
        String transfer = ttransfer.getText();
        String saldolast = show.getText();
        show.setText(""+saldolast);
        int jmltransfer = Integer.parseInt(transfer);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo-jmltransfer;
        show.setText(""+total);
        ttransfer.setText("");
    }//GEN-LAST:event_btransferActionPerformed

    private void btarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btarikActionPerformed
        // TODO add your handling code here:
        String tarik = ttarik.getText();
        String saldolast = show.getText();
        show.setText(""+saldolast);
        int jmltarik = Integer.parseInt(tarik);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo-jmltarik;
        show.setText(""+total);
        ttarik.setText("");
    }//GEN-LAST:event_btarikActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
         javax.swing.JOptionPane.showMessageDialog(null, "Terima Kasih dan Datang Kembali");
        new bank().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaldoActionPerformed
        // TODO add your handling code here:
        int saldo = 500000;
        show.setText(""+saldo);
    }//GEN-LAST:event_bsaldoActionPerformed

    private void bsetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsetorActionPerformed
        // TODO add your handling code here:
        String setor = tsetor.getText();
        String saldolast = show.getText();
        show.setText(""+saldolast);
        int jmlsetor = Integer.parseInt(setor);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo+jmlsetor;
        show.setText(""+total);
        tsetor.setText("");
    }//GEN-LAST:event_bsetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsaldo;
    private javax.swing.JButton bsetor;
    private javax.swing.JButton btarik;
    private javax.swing.JButton btransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel show;
    private javax.swing.JTextField tsetor;
    private javax.swing.JTextField ttarik;
    private javax.swing.JTextField ttransfer;
    // End of variables declaration//GEN-END:variables
}
